run:
  timeout: 5m
  tests: false
  skip-files:
    - 'internal/config/http_config.go'
linters:
   enable-all: true
   disable:
     - cyclop
     - depguard
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - gci
     - lll
     - gofumpt
     - gochecknoinits
     - gochecknoglobals
     - goerr113
     - godox
     - gomnd
     - nakedret
     - musttag
     - nlreturn
     - nonamedreturns
     - varnamelen
linters-settings:
   estif:
     min-complexity: 4
   maligned:
     suggest-new: true
