run:
  timeout: 5m
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  enable:
    - funlen
    - dogsled
    - dupl
    - whitespace
    - wsl
    - exportloopref
  disable:
    - scopelint
  presets:
    - bugs
    - unused
  fast: false
